---
- name: Instalacao jenkins
  hosts: automation
  tasks:
   - name: Install deps
     yum:
      name: "{{ item }}"
      state: present
     with_items:
       - wget
       - java
       - git
    

   - name: install repo
     command: "wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo"   
    
   - name: Instalando key
     command: "rpm --import https://jenkins-ci.org/redhat/jenkins-ci.org.key"

   - name: Instalando jenkins
     yum:
      name: jenkins
