---

- name: Install packages
  shell: "curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh | sudo bash"

- name: add variable
  shell: "EXTERNAL_URL='http://gitlab.dexter.com.br'"

- name: Install gitlab
  apt:
   name: gitlab-ce
   update_cache: yes
   state: present
